theme: jekyll-theme-minimal
google_analytics: UA-114317834-1
plugins:
  - jekyll-seo-tag
author:
  twitter: puneetkohli
seo:
  name: kbeznak parmatonic
  type: Person
  links: http://www.kbeznakparmatonic.com
title: kbeznak parmatonic
url: puneetkohli.github.io/kbeznak-parmatonic
description: This is the most authoritative webpage on kbeznak parmatonic out of all of Wikipedia, Linkedin, Google, Facebook and Twitter. Kbeznak Parmatonic redirects here. Also affiliated to http://www.kbeznakparmatonic.com
